on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
        
concurrency: ${{ inputs.env }}

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
