on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true



jobs:
  job-name:
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.env }}
    steps:
      - run: echo 'done'
